### ISSUE TITLE
[BUG] Environment variable AWS_PROFILE not respected

### ISSUE THREAD

**Issue by andrejvanderzee** [opensearch-project/terraform-provider-opensearch#99]
### What is the bug?

The provider does not take into account `AWS_PROFILE` environment variable. Instead, we must explicitly set it in the provider config like this:

```
provider "opensearch" {
  url                         = var.opensearch_url
  healthcheck        = "false"
  aws_region          = "eu-west-1"
  aws_assume_role_arn = "arn:aws:iam::****:role/opensearch-master"
  aws_profile         = "management"
}
```

### How can one reproduce the bug?

Remove `aws_profile` from the configuration above and do a `export AWS_PROFILE=management`. That will result in: 

```
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

### What is the expected behavior?

Override the `aws_profile` setting in the provider configuration, if any.

### What is your host/environment?

Ubuntu 22.04

**Comment by andrejvanderzee** [comment]
The same holds for using the `aws_assume_role_arn` with environment variables `AWS_ACCESS_KEY_ID` and `AWS_ACCES_KEY`. Only via the `~/.aws/credentials file` it works.

**Comment by peterzhuamazon** [comment]
@prudhvigodithi to take a look on this.

**Comment by prudhvigodithi** [comment]
@massimob76 @ekirmayer can you please add your thoughts ?
Thank you

**Comment by massimob76** [comment]
@prudhvigodithi @andrejvanderzee that should be fixed by #87

**Comment by estebane-frb** [comment]
Hi @prudhvigodithi I just tried release 2.1.0 and unfortunately am still getting this error: 

[INFO] Failed to put role mapping: NoCredentialProviders: no valid providers in chain. Deprecated.

**Comment by prudhvigodithi** [comment]
Thanks @estebane-frb for the feedback, adding @massimob76  @rblcoder to please take a look.

**Comment by rblcoder** [comment]
I am able to specify AWS profile both using 

```
provider "opensearch" {
  url = "url"
  healthcheck        = "false"
  aws_region          = "region"
  aws_profile = "dev"
  aws_assume_role_arn = "role arn"
  aws_assume_role_external_id = "external id"
  version_ping_timeout = "10"

}
```
as well as 

```
export AWS_PROFILE=dev
```

and 
```
provider "opensearch" {
  url = "url"
  healthcheck        = "false"
  aws_region          = "region"
  aws_assume_role_arn = "role arn"
  aws_assume_role_external_id = "external id"
  version_ping_timeout = "10"
}
```

**Comment by falcocoris** [comment]
can't get it to work, i'm getting the following error : 

│ Error: HTTP 403 Forbidden: Permission denied. Please ensure that the correct credentials are being used to access the cluster.

I can make it work using access_keys or basic auth but it doesn't meet our security requirements, which are, using IAM identity center.

Any idea what's wrong here ? Either it is isn't using the profile, or there's a missing link somewhere behind that (i'm thinking of the application layer of IAM identity center)

**Comment by rblcoder** [comment]
@falcocoris could you please share the terraform provider configuration you are using?

**Comment by falcocoris** [comment]
```
provider "opensearch" {
  url                               = "https://vpc-blabla.eu-west-1.es.amazonaws.com"
  aws_region                 = "eu-west-1"
  healthcheck                = false
  version_ping_timeout = "10"
}
```

and my aws config file is like this : 

```
[default]
sso_session = mycompany
sso_account_id = my_aws_account_id
sso_role_name = AdministratorAccess
region = eu-west-1
[sso-session mycompany]
sso_start_url = https://blabla.awsapps.com/start
sso_region = eu-west-1
sso_registration_scopes = sso:account:access
[profile dev]
region = eu-west-1
sso_session = enlaps
sso_account_id = my_aws_account_id
sso_role_name = AdministratorAccess
[dev]
region = eu-west-1
sso_session = enlaps
sso_account_id = my_aws_account_id
sso_role_name = AdministratorAccess

```

**Comment by rblcoder** [comment]
@falcocoris Using SSO works when OpenSearch allows access to the role ARN created by IAM Identity Center 
```
arn:aws:iam::aws-account-ID:role/aws-reserved/sso.amazonaws.com/aws-region/AWSReservedSSO_permission-set-name_unique-suffix
```
https://docs.aws.amazon.com/singlesignon/latest/userguide/referencingpermissionsets.html

**Comment by falcocoris** [comment]
> ARN

that's exactly what i was missing, thx ! 

Do you think it's worth mentioning in the [provider configuration section](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs#authentication) ?

**Comment by prudhvigodithi** [comment]
Thanks @rblcoder. Also @falcocoris this is more related to how the AWS OpenSearch is created with proper working SSO settings, adding it in terraform provider docs seems to me like its deviating the scope of the terraform provider. The provider is is cloud-agnostic it targets to work for OpenSearch for any given endpoint. Also I feel that SSO configuration with AWS OpenSearch should be part of AWS docs, WDYT @falcocoris @rblcoder @bbarani ?

Also @falcocoris if you still think its better to add a one liner about this SSO setup (when used AWS OpenSearch), please feel free to raise a PR.

Thanks

**Comment by rblcoder** [comment]
@falcocoris, adding it to the OpenSearch Terraform provider documentation would deviate from its scope as it is something we are configuring in AWS. Do contribute a line on SSO configuration for AWS OpenSearch by submitting a PR, if you believe it should be there.
